# Generated by Django 3.1.6 on 2021-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210211_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
