# Generated by Django 3.1.6 on 2021-04-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210424_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
