# Generated by Django 3.1.6 on 2021-04-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentbook',
            old_name='appointment_for',
            new_name='patient',
        ),
    ]
